name: Docker Build and Push to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tags
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/oauth2-shield
          IMAGE_NAME=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')
          TAG=latest
          GIT_SHA=$(git rev-parse --short HEAD)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_ENV
          echo "tags=$IMAGE_NAME:$TAG,$IMAGE_NAME:$GIT_SHA" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.tags }}
          platforms: linux/amd64,linux/arm64

      - name: Show built images
        run: docker images
